### PR TITLE
Fixed Bug #196.  Update product version to 0.5.0 in package.json

### LINKED ISSUE #196: URL Trailing Slash
https://dev-earthquake.cr.usgs.gov/ws/designmaps

(without a trailing slash) seems to be missing CSS.

### PR DESCRIPTION
**Pull request by jcaple-devtech**
Fixes #196 

I also took the liberty to update the version in packages.json.

### CODE REVIEW

File: src/lib/web-service.js [hunk 1]
```diff
@@ -272,6 +272,11 @@ const WebService = function (options) {
     // handle dynamic requests
     app.get(_this.mountPath + '/:method', _this.get);
 
+    // Redirect to index.html
+    app.get(this.mountPath, (req, res) => {
+      res.redirect(_this.mountPath + '/index.html');
+    });
+
     // rest fall through to htdocs as static content.
     app.get([_this.mountPath, _this.mountPath + '/index.html'], (req, res) => {
```
Comment (emartinez-usgs) [inline src/lib/web-service.js]: Since we're now redirecting on line 277 above, maybe the first `_this.mountPath` here should include the trailing slash?
```
app.get([_this.mountPath + '/', _this.mountPath + '/index.html'], (req, res) => {
```

Comment (emartinez-usgs) [reply src/lib/web-service.js]: Functionally it should behave the same. The reason for the change is to make it technically correct. If `_this.mountPath` is always redirected, then the first item in the subsequent `get` array configuration becomes meaningless. It can possibly be removed if doing so would not alter the behavior.
